// Code generated by Wire. DO NOT EDIT.

//go:build !wireinject

package wire

import (
	"github.com/gofiber/fiber/v2"
	"go.uber.org/zap"

	"project/internal/api"
	"project/internal/api/handler"
	"project/internal/config"
	"project/internal/repo"
	"project/internal/service"
	"project/pkg/logger"
)

func InitializeApp() (*fiber.App, *zap.Logger, *config.Config, error) {
	cfg, err := config.Load()
	if err != nil {
		return nil, nil, nil, err
	}
	loggerLogger, err := logger.NewLogger(cfg)
	if err != nil {
		return nil, nil, nil, err
	}
	userRepo := repo.NewUserRepo()
	userService := service.NewUserService(userRepo)
	userHandler := handler.NewUserHandler(userService, loggerLogger)
	app := api.NewApp(loggerLogger, userHandler)
	return app, loggerLogger, cfg, nil
}
